// CALCULATED AFTER COMPETITION WINDOW ENDS
// 1. GET USER DAILY SCORES USING /api/getUserDailyScores
// 2. WindowTotalScore FOR GIVEN USER = SUM(USER SCORES DURING ALL DAYS IN WINDOW)
// 3. GET THIS FOR ALL USERS IN THE DB FOR THE GIVEN COMPETITION AND SUM IT
// 3. TP(TOURNAMENT POINTS) = ((TP_POOL * (WINDOW SCORE OF GIVEN USER)/(SUM OF WINDOW SCORES OF ALL USER)))
// 4. LP(LEADERBOARD POINTS, NORMALIZED TO %) = 100 * (WINDOW SCORE OF USER/(MAX(WINDOW SCORE)))
// RETURN TP + LP AND UPDATE THAT COMPETITION'S FINALIZED TP + LP IN THE DB FOR THE USER, UPDATE USER STATE WITH UPDATING TOTAL USER TP